const complimentsArr = [
	'Woah. Very good',
	'Excellent',
	'Brilliant',
	'Marvellous',
	'Extraordinary',
	'Terrific',
	'Fantastic',
	'Amazing',
	'You genius, you',
	'Awesome',
	'Good job',
	'Unbelievable',
	'Incredible',
	'Spectacular',
	'Remarkable',
	'Fabulous',
	'Phenomenal',
	'Sensational',
	'Gorgeous',
	'Impressive',
	'Outstanding',
	'Magnificent',
	'Splendid',
	'Good work',
	'Phenomenal',
	'Superb',
	'You superhuman, you',
	'OMG',
	'Wowza',
	'Absolutely stunning',
	'Sweet',
]
const pityArr = [
	'Oh no!',
	'Oh nooooo!',
	'Nope.',
	'Too bad!',
	'Almost. Almost.',
	'Quel malheur!',
	'Bummer',
	'Oooh, that was close!',
	'You were sooo close!',
	'Aaaargh, next time.',
	'Sorryyy …',
	'So sorry …',
	'Apologies.',
	'Pardon.',
	'Uh-oh.',
	'Sad but true:',
]
const cheesyQuotesArr = [
	'Rome wasn’t built in a day.',
	'It happens to the best of us.',
	'You’ll be quicker next round.',
	'We still believe in you.',
	'We know this is tough, but you’re tougher.',
	'You got this!',
	'The next round will be your round.',
	'In the middle of difficulty lies opportunity.',
	'Optimism is the faith that leads to success.',
	'We believe in you. And unicorns. But mostly you.',
	'True champions, like the sun, cannot be eclipsed for long.',
	'We’ve seen slower people play this game.',
	'A champion is defined not by their wins but by how they recover when they fall.',
	'This difficult time is just a stepping stone along the path to something greater.',
	'It doesn’t matter how slow you go as long as you don’t stop.',
	'Faith can move mountains.',
	'This, too, shall pass.',
	'One day, you’ll look back on this period in your life and be so glad that you never gave up.',
	'The only time you run out of chances is when you stop taking them.',
	'Every round may not be a good round, but there’s something good in every round.',
	'You grow through what you go through.',
	'Sometimes you win, sometimes you learn.',
	'Success doesn’t come from what you do occasionally. It comes from what you do consistently.',
	'Every accomplishment starts with the decision to try.',
	'Sometimes you win, sometimes you learn.',
	'The best view comes after the hardest climb.',
	'It doesn’t matter how far down you fall as long as you can still look up and see the stars.',
]
